apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "RabbitMQUsername"
        objectType: "secretsmanager"
        objectAlias: "rabbitmq-username"
      - objectName: "RabbitMQPassword"
        objectType: "secretsmanager"
        objectAlias: "rabbitmq-password"
      - objectName: "MSSQL-SA-PASSWORD"
        objectType: "secretsmanager"
        objectAlias: "mssql-password"
  secretObjects:
    - secretName: mssql-password
      type: Opaque
      data:
        - objectName: "mssql-password"
          key: mssql-password
    - secretName: rabbit-password
      type: Opaque
      data:
        - objectName: "rabbitmq-password"
          key: rabbit-password
    - secretName: rabbit-username
      type: Opaque
      data:
        - objectName: "rabbitmq-username"
          key: rabbit-username
